ssu_backup: ssu_backup.o linkedlist.o
	gcc ssu_backup.o linkedlist.o -o ssu_backup -lpthread
ssu_backup.o: ssu_backup.c
	gcc ssu_backup.c -c -lpthread
linkedlist.o: linkedlist.c
	gcc linkedlist.c -c

